[".delta/themes.gitconfig"]
type = "file"
url = "https://raw.githubusercontent.com/dandavison/delta/master/themes.gitconfig"
refreshPeriod = "168h"
[".alacritty-colorscheme"]
type = "archive"
url = "https://github.com/eendroroy/alacritty-theme/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".config/bat"]
type = "archive"
url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
include = ["**/themes/*.tmTheme"]
stripComponents = 1
refreshPeriod = "168h"
[".config/iTerm2-Color-Schemes"]
type = "archive"
url = "https://github.com/mbadolato/iTerm2-Color-Schemes/archive/master.tar.gz"
include = ["**/wezterm/**"]
stripComponents = 1
refreshPeriod = "168h"
[".config/tokyonight-extras"]
type = "archive"
url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
include = ["**/extras/**"]
stripComponents = 2
refreshPeriod = "168h"
