# this file is managed in dev/dys-config
# See https://dystroy.org/blog/gg/

default_flags = "hd"

cols_order = "scdgbn"

[[verbs]]
invocation = "edit"
key = "ctrl-e"
shortcut = "e"
execution = "$EDITOR {file}"
leave_broot = false

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
key = "enter"
leave_broot = false
execution = "git diff {file}"
# execution = "git difftool -y {file}"
apply_to = "file"

[[verbs]]
invocation = "git_add"
shortcut = "ga"
key = "ctrl-a"
leave_broot = false
execution = "git add {file}"
apply_to = "file"

[[verbs]]
invocation = "git_checkout"
shortcut = "gco"
leave_broot = false
execution = "git checkout {file}"
apply_to = "file"

[[imports]]
file = "skins/solarized-light.hjson"
